### ISSUE TITLE
As an unregistered user, I want to be able to register as a user to use services available only to registered and logged-in users  

### ISSUE THREAD

**Issue by NattiShakira** [sopra-fs23-group-39/sopra-server#1]
- [ ] sopra-fs23-group-39/sopra-server#2
- [ ] sopra-fs23-group-39/sopra-client#4
- [ ] sopra-fs23-group-39/sopra-client#17
- [x] sopra-fs23-group-39/sopra-client#49

**Comment by dkuzma1** [comment]
https://github.com/sopra-fs23-group-39/sopra-client/commit/87d4b9e76423d40deba13f34c26ccd522612d10a
