### ISSUE TITLE
As a logged-in user willing to initiate a new game, I want to be able to set particular characteristics of the game choosing from available options and create a game

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-server#10]
- [ ] sopra-fs23-group-39/sopra-server#11
- [ ] sopra-fs23-group-39/sopra-client#7
- [ ] sopra-fs23-group-39/sopra-server#13
- [ ] sopra-fs23-group-39/sopra-client#6
- [ ] sopra-fs23-group-39/sopra-server#15
- [ ] sopra-fs23-group-39/sopra-client#5
- [ ] sopra-fs23-group-39/sopra-client#13
- [ ] sopra-fs23-group-39/sopra-server#27
- [ ] sopra-fs23-group-39/sopra-client#46
