### ISSUE TITLE
As a logged-in user willing to play a game, I want to be able to see the characteristics of the game and a list of other users that will participate in the game, to make the final decision if I want to participate in this game

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-server#17]
- [x] sopra-fs23-group-39/sopra-client#8
- [ ] sopra-fs23-group-39/sopra-server#22
- [x] sopra-fs23-group-39/sopra-client#10
- [ ] sopra-fs23-group-39/sopra-client#11
