### ISSUE TITLE
As a logged-in user participating in a game, I want to see the game questions and given answer choices or a field to enter an answer to be able to give my answer

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-server#36]
- [x] sopra-fs23-group-39/sopra-client#20
- [x] sopra-fs23-group-39/sopra-server#38
- [ ] sopra-fs23-group-39/sopra-server#39
- [x] sopra-fs23-group-39/sopra-server#55
- [x] sopra-fs23-group-39/sopra-server#56
- [x] sopra-fs23-group-39/sopra-server#60
- [x] sopra-fs23-group-39/sopra-client#45
- [x] sopra-fs23-group-39/sopra-client#47
- [x] sopra-fs23-group-39/sopra-client#48
- [x] sopra-fs23-group-39/sopra-server#68
