### ISSUE TITLE
As a previously registered but logged-out user, I want to be able to log in into the system with my chosen credentials (username and password) to use services and information that are available only to logged-in users

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-server#4]
- [x] sopra-fs23-group-39/sopra-server#5
- [x] sopra-fs23-group-39/sopra-client#18
- [x] sopra-fs23-group-39/sopra-server#67
