### ISSUE TITLE
As a logged-in user participating in a game and having answered a question, I want to see the right answer to the question and the scores of all the users playing this game (including my score).

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-server#40]
- [x] sopra-fs23-group-39/sopra-client#25
- [ ] sopra-fs23-group-39/sopra-client#53
- [ ] sopra-fs23-group-39/sopra-client#70
