### ISSUE TITLE
As a logged-in user, I want to be able to go to one of several sections of the web-site by choosing a corresponding action from the list of actions shown on the main page

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-server#6]
- [ ] sopra-fs23-group-39/sopra-client#3
- [ ] sopra-fs23-group-39/sopra-client#2
- [ ] sopra-fs23-group-39/sopra-client#1
- [ ] sopra-fs23-group-39/sopra-client#12
- [ ] sopra-fs23-group-39/sopra-client#38
- [ ] sopra-fs23-group-39/sopra-server#52
- [x] sopra-fs23-group-39/sopra-client#39
