### ISSUE TITLE
As a player, I want to play the game in a standardized Blitz format

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-server#90]
- [x] sopra-fs23-group-39/sopra-client#65
- [x] sopra-fs23-group-39/sopra-server#92
- [x] sopra-fs23-group-39/sopra-server#93
- [x] sopra-fs23-group-39/sopra-server#94
