### ISSUE TITLE
As a player I want to play a game where the prompt is from a tv show

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-server#95]
- [ ] sopra-fs23-group-39/sopra-client#67
- [ ] sopra-fs23-group-39/sopra-server#97
- [ ] sopra-fs23-group-39/sopra-server#98
